### ISSUE TITLE
OpenAI API Bug

### ISSUE THREAD

**Issue by Holland967** [Taewan-P/gpt_mobile#132] opened 2024-12-11 11:10 UTC
When I use the OpenAI API, an error occurred. Info as below:

```
Error: Field 'severity' is required for type with serial name 'com.aallam.openai.api.chat.ContentFilterResult', but it was missing at path: $.choices[0].content_filter_results.hate
```

Seems like OpenAI SDK for Java has some issues.

**Comment by Taewan-P** [comment] 2024-12-11 12:28
@Holland967 Hi. Thanks for the report!
Before I look into this, few questions:
- Does it happen every time? Tried using retry button?
- If so, what kind of question did you ask? (Including the system prompt)

**Comment by Taewan-P** [comment] 2024-12-18 07:05
Since there is no further updates, I will close this issue for now. I cannot reproduce the issue.

**Closed by Taewan-P** 2024-12-18 07:05 UTC
Labels: bug

**Comment by Boy-Grid** [comment] 2025-02-28 05:43
> [@Holland967](https://github.com/Holland967) Hi. Thanks for the report! Before I look into this, few questions:
> 
> * Does it happen every time? Tried using retry button?
> * If so, what kind of question did you ask? (Including the system prompt)

I also ran into the same problem. I was trying to use the DeepSeek API from Siliconflow, but received this response for both (DeepSeek-)V3 and R1.

* Does it happen every time? Tried using retry button?

Yes, I opened several sessions and switched between V3/R1, and they all went like this. Retry button didn't work either.

* If so, what kind of question did you ask?

"Hello?" in Chinese. As for the system prompt, it's also in Chinese, describing its role and regular rules. Not pasting it here as it's probably not relevent.

DeepSeek API follows the OpenAI API like many others, perhaps it's the API version difference that's causing this issue? If that's the case, allowing users to customize the request(if possible) might helps.

**Comment by Taewan-P** [comment] 2025-02-28 09:47
@Boy-Grid Actually, it might be related to the system prompt. (Not sure though)

https://techcommunity.microsoft.com/discussions/azure/azure-openai-content-filter-result-is-always-content-filter-error/4370163

Usually, there should be a "filtered" part and "severity" part in Content Filter Result like in the [following code](https://github.com/aallam/openai-kotlin/blob/f70d2f99fcf2d12e8b2c78b5e3b3c45fafb50c05/openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ContentFilterResults.kt#L6), but it seems like it is missing.

When a normal response is returned, this part should not be serialized because this part only appears when there is an error in the request or response.

So here are some additional questions for further investigation:
- What type of system prompt is it?
- Have you tried using it without any instructions in the system prompt?
- Are you able to read the logcat when the error occurs?

Also, how can I test this? If there is a way to reproduce the error on my side?

**Comment by Boy-Grid** [comment] 2025-03-06 05:19
@Taewan-P Sorry for forgetting to reply.

* What type of system prompt is it?

  I've tried several ones since then. I'll paste them at the bottom.
* Have you tried using it without any instructions in the system prompt?

  Not exactly. Since the system prompt can't be empty, I still wrote about who it is. Please view at the bottom.
* Are you able to read the logcat when the error occurs?

  Where is it? I couldn't find😂

* How to reproduce:

1. Set API URL: https://api.siliconflow.cn/v1/
2. Set API Key: (I can give you mine, if needed)
3. Set custom model to: deepseek-ai/DeepSeek-V3
4. Set temperature: 0.7
5. Set top p: 0.7
6. Set system prompt: those I pasted at the bottom

* BTW

  I also tried DeepSeek's official API in GPTMobile, and everything worked perfectly, so it seems that this issue is specific to the Siliconflow API; however the Siliconflow API works fine in CodeGPT (Proxy AI? The plugin for JetBrains IDEs), so I'm kinda confused.

* System prompts I tried:

```
(in Chinese)
你是由幻方量化开发的AI助手DeepSeek-V3，专注于提供实用信息。你的回答需遵循以下原则：  
1. 若问题涉及隐私、实时信息、专业知识（如医疗、法律）等你所不熟悉的内容，需在尝试解答之余声明自身局限性并建议权威渠道。  
2. 用口语化表达简化复杂概念，必要时用分点或举例说明。
另外，如果：
1. 用户的发言是纯英文的，除非用户特别指明（要求使用英文回答）或是任务需要（如翻译），应当仍然使用中文回答。
2. 话题与代码有关，则编程语言默认为ArkTS，脚本语言默认为Bash。
```

```
(in Chinese)
你是由幻方量化开发的AI助手DeepSeek-V3，专注于提供实用信息。
```

```
(in English)
You are the AI assistant DeepSeek-V3 developed by High-Flyer, focused on providing useful informations.
```
