### ISSUE TITLE
Error: The model `gpt-4` does not exist or you do not have access to it.

### ISSUE THREAD

**Issue by Elinca247** [Taewan-P/gpt_mobile#101] opened 2024-11-02 20:05 UTC
Hello, please help . Can't find answer anywhere. 

I add the API for open AI and this is what I get. Don't know what I'm doing wrong. 

"Error: The model `gpt-4` does not exist or you do not have access to it."

**Comment by Taewan-P** [comment] 2024-11-03 03:24
Duplicate of #98. Check your credit status and try again.

**Closed by Taewan-P** 2024-11-03 03:24 UTC
Labels: bug
