### ISSUE TITLE
Crash when copying specific content

### ISSUE THREAD

**Issue by OrO-c** [Taewan-P/gpt_mobile#93] opened 2024-10-30 12:12 UTC
**Describe the bug**
Copying text works fine, but currently crashes when copying code, which triggers a repetition every time

**To Reproduce**
1. Generate code
2. Tried to select this code
3. See error

**Expected behavior**
Copy the code normally

**Screenshots or Screen Recording**

**Additional context**

**Comment by Taewan-P** [comment] 2024-10-30 13:46
I cannot reproduce this issue. Can you explain in more details?

**Comment by nightgpt** [comment] 2024-10-30 14:09
It may take a few seconds for the crash to trigger

**Comment by Taewan-P** [comment] 2024-11-01 08:59
Do you have like a screen record that captures this issue?

**Comment by nightgpt** [comment] 2024-11-01 11:21
For some reason, my phone won't screen record and I'm contacting my friend to get him to provide a screen recording

**Comment by nightgpt** [comment] 2024-11-01 11:27
![Screenshot_20241101192244.jpg](https://github.com/user-attachments/assets/759d54c8-f11d-40e8-b771-af40fdaad501)

![Screenshot_20241101192251.jpg](https://github.com/user-attachments/assets/b4ed1025-932d-463e-8ad6-0193a2f42854)

It takes 10~20 seconds to observe the crash after selecting the text, please keep the selection state during this time, if you don't observe the crash, it may be that there is something wrong with my device, it has nothing to do with the software

**Comment by nightgpt** [comment] 2024-11-01 11:35
https://github.com/user-attachments/assets/8de26d14-5c16-44de-84c7-e7ac826350a4

**Comment by nightgpt** [comment] 2024-11-01 11:35
https://github.com/user-attachments/assets/8de26d14-5c16-44de-84c7-e7ac826350a4

**Comment by nightgpt** [comment] 2024-11-01 11:37
Are there any plans to add a crash log feature at the moment?

**Comment by Taewan-P** [comment] 2024-11-01 12:17
> Are there any plans to add a crash log feature at the moment?

Not at the moment... I haven't thought of it. Crash log feature may contain tracking feature, which is a NG for F-Droid. Also, the privacy policy must be fixed if so.

**Comment by Taewan-P** [comment] 2024-11-01 12:27
The best way report a bug is by sending logcat...

If possible,

1. Enable usb debugging on your device.
2. Connect it to your computer
3. Install android command line tool if doesn't exist
4. Execute `adb logcat` in your terminal
5. Launch the app
6. When app is crashed, see what prints on the terminal

If there are too many logs around and hard to read, try:

4. Execute `adb logcat` in your terminal. 
5. Find the process id from the logcat like this: <img width="318" alt="image" src="https://github.com/user-attachments/assets/10a671fa-c724-4c42-aa5e-ae8e51749b91">
  - Find grouped message logs like this:
  - Find the process id. From the picture, it would be 18147
6. Instead of `adb logcat`, use `adb logcat | grep 18147`
7. Same after that

**Comment by Taewan-P** [comment] 2024-11-01 12:28
Or you can use Android Studio

**Comment by Taewan-P** [comment] 2024-11-01 12:29
I tried with different devices & emulators, but I still can't reproduce this... I've been trying for more than 5 minutes each 🤔

**Comment by nightgpt** [comment] 2024-11-02 08:14
> I tried with different devices & emulators, but I still can't reproduce this... I've been trying for more than 5 minutes each 🤔

If so, the crash has nothing to do with the software, it's my phone malfunctioning

**Comment by Taewan-P** [comment] 2024-11-02 09:31
If so, I will close this issue.
Please tell me when it happens on other devices too.

**Closed by Taewan-P** 2024-11-02 09:31 UTC
Labels: bug

**Comment by OrO-c** [comment] 2024-11-02 09:57
> If so, I will close this issue.
> Please tell me when it happens on other devices too.

ok
